name: Deploy to Firebase Hosting on merge or microCMS update
'on':
  push:
    branches: [master]
  repository_dispatch:
    branches: [master]
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, generate
        run: |
          yarn install
          yarn generate
      - name: Copy Firebase configuration
        run: cp firebase.json ./dist/
      - name: List build output
        run: ls -R ./dist
      - name: deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_C0EF0 }}'
          channelId: live
          projectId: portfolio-c0ef0
          entryPoint: ./
