name: Deploy to Firebase Hosting on merge or microCMS update
'on':
  push:
    branches: [master]
  repository_dispatch:
    branches: [master]
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate static page
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      - name: yarn install, generate
        run: |
          yarn install
          yarn generate
      - name: Copy Firebase configuration
        run: cp firebase.json ./public/
      - name: List build output
        run: ls -R ./public
      - name: deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting --project=${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: ./
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
