name: Deploy to Firebase Hosting on merge or microCMS update
'on':
  push:
    branches: [master]
  repository_dispatch:
    branches: [master]
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build
        run: |
          yarn install
          yarn build
      - name: deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
